name: workflow

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    name: Run TestCafe Tests
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set test URL
        run: echo "testPage=https://knejpen-projekt.dk/test/" >> $GITHUB_ENV

      - name: Run TestCafe tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome test/*"


  deploy:
    name: Deploy Theme (after merge to main)
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to TEST via FTP
        uses: SamKirkland/FTP-deploy-Action@4.3.3
        with:
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./wp-content/themes/knejpen/
          server-dir: test/wp-content/themes/knejpen/

          protocol: ftp
          port: 21
          security: loose

          timeout: 120000
          log-level: verbose

          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**